SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES 
FROM REST_INFO 
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) AS MAX_FAVOR 
USING (FOOD_TYPE, FAVORITES) 
ORDER BY FOOD_TYPE DESC