# WHERE에 기간 조건을 거는 이유: 서브쿼리에서 선택된 차량이 해당 기간 외에도 대여되었을 가능성이 있기 때문
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                 WHERE YEAR(START_DATE)=2022 AND MONTH(START_DATE) BETWEEN 8 AND 10 
                 GROUP BY CAR_ID HAVING COUNT(HISTORY_ID)>=5) 
      AND YEAR(START_DATE)=2022 AND MONTH(START_DATE) BETWEEN 8 AND 10 
GROUP BY MONTH, CAR_ID HAVING RECORDS > 0
ORDER BY 1, 2 DESC