SELECT MEMBER_PROFILE.MEMBER_NAME, REST_REVIEW.REVIEW_TEXT, DATE_FORMAT(REST_REVIEW.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE JOIN REST_REVIEW ON REST_REVIEW.MEMBER_ID=MEMBER_PROFILE.MEMBER_ID
WHERE MEMBER_PROFILE.MEMBER_ID IN (SELECT MEMBER_ID FROM REST_REVIEW 
                                   GROUP BY MEMBER_ID HAVING COUNT(MEMBER_ID)=(SELECT COUNT(MEMBER_ID) AS CNT 
                                                                               FROM REST_REVIEW GROUP BY MEMBER_ID 
                                                                               ORDER BY CNT DESC LIMIT 1))
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC