SELECT APNT_NO, PT_NAME, PT_NO, APPOINTMENT.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT JOIN PATIENT USING(PT_NO) JOIN DOCTOR ON APPOINTMENT.MDDR_ID=DOCTOR.DR_ID
WHERE APNT_YMD LIKE "2022-04-13%" AND APNT_CNCL_YN="N" AND APPOINTMENT.MCDP_CD="CS"
ORDER BY APNT_YMD