# DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d')
# MONTH(DATE_OF_BIRTH)=3
SELECT MEMBER_ID, MEMBER_NAME, GENDER, LEFT(DATE_OF_BIRTH,10) AS DATE_OF_BIRTH FROM MEMBER_PROFILE WHERE GENDER='W' AND DATE_OF_BIRTH LIKE '%-03-%' AND TLNO IS NOT NULL ORDER BY MEMBER_ID ASC